server:
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
      repository: "https://maven.lavalink.dev/releases"
  server:
    password: "Aeternus-music"
    sources:
      youtube: false
      soundcloud: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - TVHTML5
      - MUSIC
      - ANDROID_VR
      - WEB
    oauth:
      enabled: true
      refreshToken: "1//01pVJCROVF2M-CgYIARAAGAESNwF-L9IrwH1UuDI-_D5Cb8sizqxQRBc3RMV2CUTJJVaT_YiSbh47cpMWg8VPKwrL9TkNyac6KK8"
