server:
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.4"
      repository: "https://maven.lavalink.dev/releases"
  server:
    password: "${LAVALINK_PASSWORD:Aeternus-music}"
    sources:
      youtube: false
      soundcloud: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_VR
      - WEB
      - ANDROID
      - IOS
    oauth:
      enabled: true
      refreshToken: "${YOUTUBE_REFRESH_TOKEN}"
