services:
  - type: web
    name: aeternus-lavalink
    runtime: docker
    plan: free
    healthCheckPath: /version
    envVars:
      - key: PORT
        value: "10000"
      - key: LAVALINK_PASSWORD
        generateValue: true
      - key: YOUTUBE_OAUTH_ENABLED
        value: "true"
      - key: YOUTUBE_OAUTH_SKIP_INIT
        value: "true"
      - key: YOUTUBE_REFRESH_TOKEN
        sync: false
